extends Node

enum texturas_personaje {
	CHARACTER_BASE,
	ARCHER_GREEN,
	ARCHER_PURPLE,
	HUMAN_SOLDIER_CYAN,
	HUMAN_SOLDIER_RED,
	HUMAN_WORKER_CYAN,
	HUMAN_WORKER_RED,
	MAGE_CYAN,
	MAGE_RED,
	ORC_GRUNT,
	ORC_PEON_CYAN,
	ORC_PEON_RED,
	ORC_SOLDIER_CYAN,
	ORC_SOLDIER_RED,
	SOLDIER_BLUE,
	SOLDIER_RED,
	SOLDIER_YELLOW,
	WARRIOR_BLUE,
	WARRIOR_RED,
	SLIME
}
